In [1]:
import numpy as np

In [2]:
x = np.array([[1,2],[3,4],[5,6]])

In [3]:
x.ndim

2

In [5]:
x.itemsize

4

In [7]:
x = np.array([[1,2],[3,4],[5,6]], dtype = np.float64)

In [8]:
x.itemsize

8

In [9]:
x = np.array([[1,2],[3,4],[5,6]], dtype = complex)

In [10]:
x

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [11]:
x.dtype

dtype('complex128')

In [12]:
x = np.array([[1,2],[3,4],[5,6]], dtype = np.float64)

In [13]:
x.dtype

dtype('float64')

In [14]:
x = np.array([[1,2],[3,4],[5,6]])

In [15]:
x.dtype

dtype('int32')

In [16]:
x.size

6

In [17]:
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
x.shape

(3, 2)

In [20]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
np.arange(1,10,4)

array([1, 5, 9])

In [27]:
x = np.array([[1,2],[3,4],[5,6]])

In [28]:
x.shape

(3, 2)

In [29]:
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [30]:
x.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
x.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [35]:
array=x.ravel()

In [34]:
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [36]:
array

array([1, 2, 3, 4, 5, 6])

In [37]:
x

array([[1, 2],
       [3, 4],
       [5, 6]])