In [5]:
import numpy as np

In [6]:
np.linspace(1,20,5)

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [9]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [10]:
np.diag([10,20,30,40])

array([[10,  0,  0,  0],
       [ 0, 20,  0,  0],
       [ 0,  0, 30,  0],
       [ 0,  0,  0, 40]])

In [16]:
x = np.array([[1,2],[3,4]])

In [17]:
x

array([[1, 2],
       [3, 4]])

In [18]:
np.diag(x)

array([1, 4])

In [22]:
np.random.randint(2,10,8)

array([6, 2, 5, 9, 4, 9, 8, 5])

In [26]:
np.random.rand(100)

array([0.80293598, 0.5222895 , 0.07899895, 0.99552583, 0.23097842,
       0.08158585, 0.71462446, 0.58551784, 0.35856011, 0.41618059,
       0.8602949 , 0.04889511, 0.89713343, 0.14933684, 0.51416753,
       0.40173362, 0.64777544, 0.40357771, 0.23628389, 0.90435452,
       0.10921384, 0.17947482, 0.27485052, 0.88120034, 0.90558152,
       0.80735245, 0.06788188, 0.25968524, 0.4470812 , 0.86524189,
       0.93637937, 0.33958509, 0.84277198, 0.91772956, 0.46714575,
       0.24037281, 0.14156517, 0.04993468, 0.11969908, 0.54200534,
       0.35480399, 0.54141128, 0.86756243, 0.42663555, 0.41531339,
       0.96163287, 0.42965167, 0.56823195, 0.98311104, 0.94417717,
       0.70718106, 0.84553395, 0.19137609, 0.64662394, 0.09726989,
       0.22786602, 0.63799642, 0.40551772, 0.04421209, 0.37625869,
       0.38207333, 0.92079175, 0.63501514, 0.48465283, 0.33749324,
       0.60890687, 0.92687913, 0.33500623, 0.0532131 , 0.84595016,
       0.0958975 , 0.3860412 , 0.24965152, 0.66449572, 0.33694

In [28]:
np.random.randn(60)

array([-0.46799167, -0.85519044, -0.91875467,  0.39038959, -0.12863099,
       -2.4266295 , -2.25507438, -1.08000957,  0.58293433,  1.52765049,
        0.1123291 , -0.3889834 ,  0.79851548, -1.43539527, -0.32806226,
       -0.31451363,  0.47301808, -0.09334938, -0.94781752, -0.37928635,
        0.98906162,  0.71889304,  0.19040281,  0.01658037, -2.43964126,
       -0.08894029, -0.61950993, -1.6965099 ,  1.18032605,  1.44819602,
        0.52865951, -0.76739868, -0.79548555, -0.4963138 , -2.34926766,
       -0.24719599,  0.34584012,  0.83180921,  0.17744885,  0.39593997,
       -0.01216135,  1.08751814,  1.01422851,  2.31495003, -0.67886787,
        1.28797226, -1.14011347,  0.30556952,  1.75026608, -0.50779682,
       -2.08081811,  0.35997125,  0.56225874,  0.76386268,  1.5286401 ,
       -2.5933933 , -0.68721886, -0.54026614,  0.62268002,  0.35213142])

In [41]:
np.random.seed(121)
np.random.randint(1,10,5)

array([3, 6, 9, 5, 2])